### ISSUE TITLE
Preparar ambiente de produção do chatbot

### ISSUE THREAD

**Issue by Ernzen1** [GamePog/Chatbot-ARC#7]
Clonar o repositório no servidor da disciplina para validar a estrutura dos arquivos, em especial a configuração (config.py) e dados (**data/**). Estudar variáveis de ambiente (**pyenv?**) para combinar dados sensíveis à configuração.

Depende de #4 e #11, e alguns comandos de #9 já serão vistos aqui.

**Comment by Bruno-O20** [comment]
Feito
